import {NavLink,Outlet,useNavigate} from 'react-router-dom';
<<<<<<< HEAD
import {Home,PlusSquare,Images,Palette,Wallet,LogOut,Sparkles} from 'lucide-react';
const links=[['/dashboard','Inicio',Home],['/create','Crear pieza',PlusSquare],['/designs','Mis diseños',Images],['/brand','Mi marca',Palette],['/mi-plan','Mi plan',Wallet]];
export default function AppLayout(){const nav=useNavigate();return <div className="app-shell"><aside className="sidebar"><div className="brand-lockup"><span className="logo-mark"><Sparkles/></span><span>Creator's<br/><b>Closet</b></span></div><nav>{links.map(([to,label,Icon])=><NavLink to={to} key={to}><Icon/><span>{label}</span></NavLink>)}</nav><button className="logout" onClick={()=>nav('/login')}><LogOut/>Cerrar sesión</button></aside><header className="mobile-header"><div className="brand-lockup"><span className="logo-mark"><Sparkles/></span><b>Creator's Closet</b></div><span className="avatar">AL</span></header><main className="app-main"><Outlet/></main><nav className="bottom-nav">{links.filter((_,i)=>i!==2&&i!==4).map(([to,label,Icon],i)=><NavLink to={to} key={to} className={i===1?'create-tab':''}><Icon/><span>{label.replace(' pieza','')}</span></NavLink>)}</nav></div>}
=======
import {Home,PlusSquare,Images,Palette,LogOut,Sparkles} from 'lucide-react';
import {useApp} from '../context/AppContext';
const links=[['/dashboard','Inicio',Home],['/create','Crear pieza',PlusSquare],['/designs','Mis diseños',Images],['/brand','Mi marca',Palette]];
export default function AppLayout(){const nav=useNavigate();const {logout}=useApp();const handleLogout=async()=>{await logout();nav('/login');};return <div className="app-shell"><aside className="sidebar"><div className="brand-lockup"><span className="logo-mark"><Sparkles/></span><span>Creator's<br/><b>Closet</b></span></div><nav>{links.map(([to,label,Icon])=><NavLink to={to} key={to}><Icon/><span>{label}</span></NavLink>)}</nav><button className="logout" onClick={handleLogout}><LogOut/>Cerrar sesión</button></aside><header className="mobile-header"><div className="brand-lockup"><span className="logo-mark"><Sparkles/></span><b>Creator's Closet</b></div><span className="avatar">AL</span></header><main className="app-main"><Outlet/></main><nav className="bottom-nav">{links.filter((_,i)=>i!==2).map(([to,label,Icon],i)=><NavLink to={to} key={to} className={i===1?'create-tab':''}><Icon/><span>{label.replace(' pieza','')}</span></NavLink>)}</nav></div>}
>>>>>>> 2237958386fe52fb827c503a9b5c502484e9b4b7
